version: "3.7"
services:
  web_jupyter:
    container_name: web_jupyter
    image: docker.io/jupyter/datascience-notebook:latest
    volumes:
      - ./work:/home/jovyan/work
      - ./config/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - ./config/jupyter_notebook_config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
    ports:
      - 8888:8888
    restart: always
